#!/usr/bin/env bash
#
# DEV-ONLY: install tracked shims so the app can run without a full
# chip-core wasm build, Firebase credentials, or a real catalog.
#
# Everything this script touches is either gitignored or backed up first.
# Run `dev/remove.sh` to undo all of it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "[dev] Applying development shims..."

# 1. chip-core stub -> src/chip-core.js (gitignored, safe to overwrite)
cp dev/shims/chip-core.js src/chip-core.js
echo "[dev]   installed src/chip-core.js (stub)"

# 2. Firebase placeholder -> src/config/firebaseConfig.js (gitignored)
if [ -f src/config/firebaseConfig.js ] && [ ! -f src/config/firebaseConfig.js.dev-backup ]; then
  cp src/config/firebaseConfig.js src/config/firebaseConfig.js.dev-backup
  echo "[dev]   backed up existing src/config/firebaseConfig.js"
fi
cp dev/shims/firebaseConfig.js src/config/firebaseConfig.js
echo "[dev]   installed src/config/firebaseConfig.js (placeholder)"

# 3. Auth bypass -> server/middleware/auth.js (tracked, so back it up)
if [ ! -f server/middleware/auth.js.dev-backup ]; then
  cp server/middleware/auth.js server/middleware/auth.js.dev-backup
  echo "[dev]   backed up server/middleware/auth.js"
fi
cp dev/shims/server-auth.js server/middleware/auth.js
echo "[dev]   installed server/middleware/auth.js (bypass)"

# 4. Optional skia-canvas patch for server/index.js (reversible, no backup)
node dev/patch-server.js

# 5. Dev user -> src/components/UserProvider.js (reversible, no backup)
node dev/patch-user-provider.js

# 5b. Silent SID fallback (reversible, no backup)
node dev/patch-sid-stub.js

# 5c. Browser test hooks (window.__cpDev); staged file + reversible patch
cp dev/shims/devtools.js src/chip-player-devtools.js
node dev/patch-devtools.js

# 6. Seed sqlite databases (catalog.db is built separately by build-music.js)
node dev/seed-dbs.js

# 7. server/.env.local (gitignored)
if [ ! -f server/.env.local ]; then
  cat > server/.env.local <<EOF
# DEV-ONLY, generated by dev/apply.sh
BROWSE_LOCAL_FILESYSTEM=false
LOCAL_CATALOG_ROOT='$ROOT/catalog'
LOCAL_SOUNDFONT_ROOT='$ROOT/public/soundfonts'
LOCAL_CLIENT_BUILD_ROOT='$ROOT/public'
EOF
  echo "[dev]   wrote server/.env.local"
else
  echo "[dev]   server/.env.local already exists; leaving as-is"
fi

# 8. Sample catalog (gitignored) + catalog db
mkdir -p catalog
if [ -f game-music-emu/test.nsf ] && [ ! -f catalog/test.nsf ]; then
  cp game-music-emu/test.nsf catalog/test.nsf
  echo "[dev]   copied game-music-emu/test.nsf into catalog/"
fi
if [ ! -f server/catalog.db ]; then
  echo "[dev]   building server/catalog.db..."
  node scripts/build-music.js || echo "[dev]   WARNING: build-music.js failed; add files to catalog/ and rerun."
fi

echo "[dev] Done. Start with: npm run dev"
